
//construccion de array para elementos a mostrar en la app

export const mockItems = [
  { id: 1, name: 'FRASE PUBLICITARIA', price: 200000, text: 'Utilizando una intención promocional que pone en alerta al oyente y lo estimula a prestar atención al producto con una voz enérgica y agradable que invade con alegría.', imageUrl: 'https://lavozdecaceres.cl/wp-content/uploads/2019/08/caceres-Bio-izq.jpg' },
  { id: 2, name: 'SPOT TV DIGITAL', price: 300000, text: 'Desarrollar una idea, empatizar con lo que vuestros clientes esperan del producto e impulsar un interés más allá de lo que la imagen puede transmitir, conexión.', imageUrl: 'https://media.licdn.com/dms/image/D4E05AQHDGZS85b57Bg/feedshare-thumbnail_720_1280/0/1681347018085?e=2147483647&v=beta&t=cRlA2oBsWdEZNJuMIQaZ2o1ZH4_F3E-HsvzhpR95WhI' },
  { id: 3, name: 'LOCUCIÓN VIDEO INSTITUCIONAL', price: 280000, text: 'Desarrollar una idea, empatizar con lo que vuestros clientes esperan del producto e impulsar un interés más allá de lo que la imagen puede transmitir, conexión.', imageUrl: 'https://lavozdecaceres.cl/wp-content/uploads/2019/08/caceres-Bio-derecha.jpg' },
  { id: 4, name: 'LOCUCION DE DOCUMENTALES', price: 150000, text: 'Informativo, narrativo, artístico… hay muchas formas de contar una historia, es cuestión de fundirse con el proyecto y sentir el mensaje como propio.', imageUrl: 'https://lavozdecaceres.cl/wp-content/uploads/2019/08/mario-caceres-Créditos-Vlog.jpg' },
  { id: 5, name: 'PERSONAJE ANIMADO', price: 350000, text: 'Si se quiere, una de las tareas más complejas de la locución. Requiere inyectar personalidad, emociones, objetivos a un otro. Es ser alguien más por un momento.', imageUrl: 'https://media.licdn.com/dms/image/C4E05AQHTJr-0c9APMQ/feedshare-thumbnail_720_1280/0/1647432056167?e=2147483647&v=beta&t=Ar-6ytLplWFlXkudieMT-rJ1p_YUihRA65iuyJBLN8c' },
  { id: 6, name: 'DOBLAJE', price: 250000, text: 'Acentos e intenciones que quedarán marcadas sin importar el idioma', imageUrl: 'https://www.chileactores.org/wp-content/uploads/2020/05/MG_91212-1.jpg' },
  { id: 7, name: 'LOCUCIÓN INTERNACIONAL', price: 500000, text: 'Acento neutro latinoamericano para campañas de difusión internacional.', imageUrl: 'https://i.ytimg.com/vi/Bl_LDLqLgIs/maxresdefault.jpg' },
  { id: 8, name: 'SEO', price: 600000, text: 'Te posicionamos en buscadores para que seas el primero en la mente y pantallas de tus consumidores.', imageUrl: 'https://kinsta.com/es/wp-content/uploads/sites/8/2016/12/seo-tips.jpeg', category: 'Web' },
  { id: 9, name: 'CAMPAÑA DIGITAL', price: 450000, text: 'No puedes dejar de estar presente, nos ajustamos a tu presupuesto de inversión para maximizar tus resultados.', imageUrl: 'https://www.prospectfactory.com.mx/wp-content/uploads/2019/10/shutterstock_548073523-1000x500.jpg', category: 'Coach' },
  { id: 10, name: 'MICROSITIO', price: 550000, text: 'Básico pero poderoso, escalable.', imageUrl: 'https://clevertap.com/wp-content/uploads/2019/09/microsite-blog-header.png', category: 'Web' },
  { id: 11, name: 'ASESORIAS', price: 480000, text: 'En cualquier etapa de tu emprendimiento, ahí estaremos contigo, no dudes en agendar.', imageUrl: 'https://www.copmadrid.org/wp/wp-content/uploads/2020/09/coaching.jpg', category: 'Coach' },
  { id: 12, name: 'APLICACIONES', price: 920000, text: 'Conversamos tu idea y la desarrollamos en las plataformas y lenguajes que necesites con los más altos estandares de seguridad.', imageUrl: 'https://blog.chevyplan.com.co/wp-content/uploads/2020/08/apps.jpg', category: 'Web' },
  ];